### ISSUE TITLE
주문 (Detailed Spells) 파트 설명 부분 접기/펴기 관련 코드 문제

### ISSUE THREAD

**Issue by ssgtamya** [alledaten/coc7th_code_refectoring#6]
>체크박스와 라벨을 생성하고 체크박스를 라벨 안에 넣어 생성, 라벨에 버튼 형태를 구현하는 CSS를 주었습니다.
(input id - label for로 연결하는 기능이 있으나 롤20에서는 id 사용을 지양하기 때문에 이와 같이 시도)
라벨(버튼) 클릭 시 체크박스 체크됨->.spell-desc-hide:checked  .spell-description-area의 display:block이 연동 -> 설명란 펴기/접기가 될 것이라 생각했지만...

```html
<!---------------------------- HTML ----------------------------->
<fieldset class="repeating_spells">                
            <div class="spell-area">
                <label class="spell-desc-button">
                    <input class="spell-desc-hide" type="checkbox">▶
                </label>

                <!--중간 코드 생략-->

            <div class="spell-description-area">
                <div>
                    <textarea name="attr_spelldescription" data-i18n-placeholder ="description-u"></textarea>
                </div>
            </div>          
            <hr></hr>
        </fieldset>`
```
```css
/*--------------------------- CSS ---------------------------*/
.spell-desc-hide {
        display:none;
}

.spell-description-area {
        display:none;
}

.spell-desc-hide:checked  .spell-description-area {
        display:block;
}
```
### 실패 상황 및 요인 
- input="checkbox"인 .spell-desc-hide를 display:none으로 화면에서 숨기려 했으나 숨겨지지 않음
- 이후 .spell-desc-hide를 display:block으로 하고 접기/펴기 기능만 구동하는지 재확인했으나 체크박스가 체크되어도 설명 란이 펴지지 않음 (.spell-description-area의 display:block이 구현되지 않음)
- 서치 결과 label과 .spell-description-area가 형제 관계여야 구현이 된다는 정보가 있었으나 두 개체를 형제 관계로 구현하면서 기존의 형태를 유지하려면  기존 html과 css를 전부 고쳐야 하는 문제가 있습니다.

**Comment by alledaten** [comment]
순서대로 기술하겠습니다.

### input="checkbox"인 .spell-desc-hide를 display:none으로 화면에서 숨기려 했으나 숨겨지지 않음

Roll20의 input 요소는 `.ui-dialog .charsheet input` 의 클래스 3단계로 이루어져 있습니다.  
`.spell-desc-hide` 는 클래스 1단계이므로 적용우선순위가 낮습니다.

### 접기/펴기 기능 구동

```css
.spell-desc-hide:checked ~ .spell-description-area {
        display:block;
}
```

이 CSS가 적용되기 위해서는 `.spell-desc-hide`와 `.spell-description-area`가 형제관계여야하므로, Roll20 변수인 `attr_` 를 이용해 같은 값을 받아오는 `.spell-desc-hide` 요소를 만들어 `.spell-description-area`의 형제요소로 추가해야 합니다.


```html
<!---------------------------- HTML ----------------------------->
<fieldset class="repeating_spells">                
            <div class="spell-area">
                <label class="spell-desc-button">
                    <input class="spell-desc-hide" type="checkbox" name="attr_spell_flag">▶
                </label>

                <!--중간 코드 생략-->
            <input class="spell-desc-hide" type="checkbox" name="attr_spell_flag">
            <div class="spell-description-area">
                <div>
                    <textarea name="attr_spelldescription" data-i18n-placeholder ="description-u"></textarea>
                </div>
            </div>          
            <hr />
</fieldset>
```

```css
/*--------------------------- CSS ---------------------------*/
.ui-dialog .charsheet input.spell-desc-hide {
        display:none;
}

.spell-description-area {
        display:none;
}

.spell-desc-hide:checked ~ .spell-description-area {
        display:block;
}
```
